### ISSUE TITLE
Question on: The tutorial you need to maximize your use of R's vectors (CC273)

### ISSUE THREAD

**Issue by FlippieCoetser** [riffomonas/code_club#8]
Hi Pat, I very much enjoyed the YouTube video you made about vector performance. I work in the healthcare domain at Philips, a health tech provider. I am a qualified clinical engineer and have done tons of data analytics with R. However, during the last three years, I have shifted efforts into developing enterprise-level applications using R. My main interest is more around the topic of architecture design and coding patterns using R. Recently I have also done a deep dive in the internal workings for R and how it stored variables in memory. I have learned a lot and am happy to share those with others. **My question is if contributions are welcome, and if so, do you have suggestions on how I can contribute?**

**Comment by pschloss** [comment]
Hi Flippie - thanks for your interest in this project! Could you perhaps
write a blog post that you could host somewhere and get me the link to read
what you've found? I'm not sure how much more benchmarking I'll be doing
past the next 2 or 3 episodes, but it would be interesting to see what you
came up with.

Thanks,
Pat

**Comment by FlippieCoetser** [comment]
This is a great suggestion! I already have the information scattered across my machine. For now, I focus on vectors but include memory and performance profiling, as well as the data structure used `under the hood` to represent the different vector types.  I'll consolidate all the material and share a copy with you. It will take me some time as I want to make sure it is suitable for wider consumption. Once again, thanks for the great videos!
